package deputyapp.deputyapp.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "AUTHORISATION_SHA1".
 */
public class AuthorisationSha1 {

    private String sha1;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AuthorisationSha1() {
    }

    public AuthorisationSha1(String sha1) {
        this.sha1 = sha1;
    }

    public String getSha1() {
        return sha1;
    }

    public void setSha1(String sha1) {
        this.sha1 = sha1;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
