package deputyapp.deputyapp.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BUSINESS".
 */
public class Business {

    private Long id;
    private String name;
    private String logo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Business() {
    }

    public Business(Long id) {
        this.id = id;
    }

    public Business(Long id, String name, String logo) {
        this.id = id;
        this.name = name;
        this.logo = logo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
