package deputyapp.deputyapp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import deputyapp.deputyapp.dao.AuthorisationSha1;
import deputyapp.deputyapp.dao.Business;
import deputyapp.deputyapp.dao.PrevShiftsData;

import deputyapp.deputyapp.dao.AuthorisationSha1Dao;
import deputyapp.deputyapp.dao.BusinessDao;
import deputyapp.deputyapp.dao.PrevShiftsDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig authorisationSha1DaoConfig;
    private final DaoConfig businessDaoConfig;
    private final DaoConfig prevShiftsDataDaoConfig;

    private final AuthorisationSha1Dao authorisationSha1Dao;
    private final BusinessDao businessDao;
    private final PrevShiftsDataDao prevShiftsDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        authorisationSha1DaoConfig = daoConfigMap.get(AuthorisationSha1Dao.class).clone();
        authorisationSha1DaoConfig.initIdentityScope(type);

        businessDaoConfig = daoConfigMap.get(BusinessDao.class).clone();
        businessDaoConfig.initIdentityScope(type);

        prevShiftsDataDaoConfig = daoConfigMap.get(PrevShiftsDataDao.class).clone();
        prevShiftsDataDaoConfig.initIdentityScope(type);

        authorisationSha1Dao = new AuthorisationSha1Dao(authorisationSha1DaoConfig, this);
        businessDao = new BusinessDao(businessDaoConfig, this);
        prevShiftsDataDao = new PrevShiftsDataDao(prevShiftsDataDaoConfig, this);

        registerDao(AuthorisationSha1.class, authorisationSha1Dao);
        registerDao(Business.class, businessDao);
        registerDao(PrevShiftsData.class, prevShiftsDataDao);
    }
    
    public void clear() {
        authorisationSha1DaoConfig.getIdentityScope().clear();
        businessDaoConfig.getIdentityScope().clear();
        prevShiftsDataDaoConfig.getIdentityScope().clear();
    }

    public AuthorisationSha1Dao getAuthorisationSha1Dao() {
        return authorisationSha1Dao;
    }

    public BusinessDao getBusinessDao() {
        return businessDao;
    }

    public PrevShiftsDataDao getPrevShiftsDataDao() {
        return prevShiftsDataDao;
    }

}
